### ISSUE TITLE
Differences from older SediScraper?

### ISSUE THREAD

**Issue by jpmckinney** [Jon1701/SediScraperJS#1]
I'm curious to view bulk SEDI data, and was wondering whether I should look at this scraper or your older scraper at https://github.com/Jon1701/SediScraper

**Comment by Jon1701** [comment]
The older one, but it hasn't been maintained, and has failed to get the SEDI data for the past few months. It really isn't meant to scrape all the data, it just gets a list of Insiders issued New Stock Options, and  gets company addresses.
